In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
from onnx import numpy_helper
import numpy as np

# The protobuf definition can be found here:
# https://github.com/onnx/onnx/blob/master/onnx/onnx.proto

In [2]:
# Create one input (ValueInfoProto)
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 2])

# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 4])

# Create a node (NodeProto)
node_def = helper.make_node(
    'Pad', # node name
    ['X'], # inputs
    ['Y'], # outputs
    mode='constant', # Attributes
    value=1.5,
    pads=[0, 1, 0, 1],
)

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [node_def],
    "test-model",
    [X],
    [Y],
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def,
                              producer_name='onnx-example')

print('The ir_version in model: {}\n'.format(model_def.ir_version))
print('The producer_name in model: {}\n'.format(model_def.producer_name))
#print('The graph in model:\n{}'.format(model_def.graph))
onnx.checker.check_model(model_def)
print('The model is checked!')

The ir_version in model: 3

The producer_name in model: onnx-example

The model is checked!


In [3]:
#helper.make_graph?
helper.make_graph(nodes, name, inputs, outputs, initializer=None, doc_string=None, value_info=[])

NameError: name 'nodes' is not defined

In [7]:
#helper.make_node?
#helper.make_node(op_type, inputs, outputs, name=None, doc_string=None, **kwargs)

In [45]:
np.ones((1,2,3,3), dtype=float)
numpy_helper.from_array(np.ones((1,2,3,3), dtype=float))

dims: 1
dims: 2
dims: 3
dims: 3
data_type: DOUBLE
raw_data: "\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?\000\000\000\000\000\000\360?"

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
from onnx import numpy_helper
import numpy as np

In [4]:
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 2])
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 2])
node=[]
node.append(onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['mul0w'],
    value=numpy_helper.from_array(np.ones((2,2), dtype=np.float32))
))
node.append(onnx.helper.make_node(
    'MatMul',
    inputs=['X', 'mul0w'],
    outputs=['mul0'],
))
'''node.append(onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['addb'],
    value=numpy_helper.from_array(np.ones((2), dtype=np.float32))
))
node.append(onnx.helper.make_node(
    'Add',
    inputs=['matmul', 'addb'],
    outputs=['add'],
))'''
node.append(onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['mul1w'],
    value=numpy_helper.from_array(np.ones((2,2), dtype=np.float32))
))
node.append(onnx.helper.make_node(
    'MatMul',
    inputs=['mul0', 'mul1w'],
    outputs=['mul1'],
))
node.append(onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['mul2w'],
    value=numpy_helper.from_array(np.ones((2,2), dtype=np.float32))
))
node.append(onnx.helper.make_node(
    'MatMul',
    inputs=['mul0', 'mul2w'],
    outputs=['mul2'],
))
node.append(onnx.helper.make_node(
    'Add',
    inputs=['mul2', 'mul1'],
    outputs=['add'],
))
node.append(onnx.helper.make_node(
    'LeakyRelu',
    inputs=['add'],
    outputs=['LeakyRelu'],
    alpha=0.0
))

node.append(onnx.helper.make_node(
    'Softmax',
    inputs=['LeakyRelu'],
    outputs=['Y'],
))
model_def = helper.make_model(helper.make_graph(node,"test-model",[X],[Y],),producer_name='onnx-example')
onnx.checker.check_model(model_def)

In [3]:
import caffe2.python.onnx.backend as backend
import numpy as np

rep = backend.prepare(model_def, device="CPU") # or "CPU"
# For the Caffe2 backend:
#     rep.predict_net is the Caffe2 protobuf for the network
#     rep.workspace is the Caffe2 workspace for the network
#       (see the class caffe2.python.onnx.backend.Workspace)
outputs = rep.run(np.ones((2,2)).astype(np.float32))
# To run networks with more than one input, pass a tuple
# rather than a single numpy ndarray.
print(outputs[0])

ModuleNotFoundError: No module named 'caffe2'

In [3]:
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [3, 1, 4, 4])
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [3, 2, 2, 2])
#const = helper.make_tensor_value_info('constant255', TensorProto.FLOAT, [1])

const255 = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['normlayer'],
    name='',
    value=onnx.helper.make_tensor(
        name='const_tensor',
        data_type=onnx.TensorProto.FLOAT,
        dims=[1],
        vals=[0.1],
    ),
)

normlayer = onnx.helper.make_node(
    op_type='Div',
    inputs=['X', 'normlayer'],
    outputs=['normx'],
    name='',
)

conv0W = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['W'],
    name='',
    value=numpy_helper.from_array(np.ones((2,1,3,3), dtype=np.float32))
)

conv0 = onnx.helper.make_node(
    'Conv',
    inputs=['normx', 'W'],
    outputs=['conv0'],
    kernel_shape=[3, 3],
    # Default values for other attributes: strides=[1, 1], dilations=[1, 1], groups=1
    pads=[1, 1, 1, 1],
)

pooling0 = onnx.helper.make_node(
    'MaxPool',
    inputs=['conv0'],
    outputs=['pooling0'],
    kernel_shape=[2, 2],
    strides=[2, 2],
)
leakyRelu = onnx.helper.make_node(
    'LeakyRelu',
    inputs=['pooling0'],
    outputs=['leakyRelu'],
    alpha=0.0
)

Bn0s = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['Bn0s'],
    name='',
    value=numpy_helper.from_array(np.ones((2), dtype=np.float32))
)
Bn0b = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['Bn0b'],
    name='',
    value=numpy_helper.from_array(np.ones((2), dtype=np.float32))
)
Bn0mean = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['Bn0mean'],
    name='',
    value=numpy_helper.from_array(np.ones((2), dtype=np.float32))
)
Bn0var = onnx.helper.make_node(
    op_type='Constant',
    inputs=[],
    outputs=['Bn0var'],
    name='',
    value=numpy_helper.from_array(np.ones((2), dtype=np.float32))
)
bn0 = onnx.helper.make_node(
    'BatchNormalization',
    inputs=['leakyRelu', 'Bn0s', 'Bn0b', 'Bn0mean', 'Bn0var'],
    outputs=['Y'],
)

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [const255,normlayer,conv0W,conv0,pooling0,leakyRelu,Bn0s,Bn0b,Bn0mean,Bn0var,bn0],
    "test-model",
    [X],
    [Y],
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def,
                              producer_name='onnx-example')
onnx.checker.check_model(model_def)

In [4]:
model_def.graph.node[2]

output: "W"
op_type: "Constant"
attribute {
  name: "value"
  t {
    dims: 2
    dims: 1
    dims: 3
    dims: 3
    data_type: FLOAT
    raw_data: "\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?"
  }
  type: TENSOR
}

In [5]:
model_def.graph.node[2].attribute[0]

name: "value"
t {
  dims: 2
  dims: 1
  dims: 3
  dims: 3
  data_type: FLOAT
  raw_data: "\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?"
}
type: TENSOR

In [6]:
model_def.graph.node[2].attribute[0].t

dims: 2
dims: 1
dims: 3
dims: 3
data_type: FLOAT
raw_data: "\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?\000\000\200?"

In [7]:
numpy_helper.to_array(model_def.graph.node[2].attribute[0].t)

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)

In [9]:
import caffe2.python.onnx.backend as backend
import numpy as np

rep = backend.prepare(model_def, device="CPU") # or "CPU"
# For the Caffe2 backend:
#     rep.predict_net is the Caffe2 protobuf for the network
#     rep.workspace is the Caffe2 workspace for the network
#       (see the class caffe2.python.onnx.backend.Workspace)
outputs = rep.run(np.ones((4,1,4,4)).astype(np.float32))
# To run networks with more than one input, pass a tuple
# rather than a single numpy ndarray.
print(outputs[0])

[[[[89.99956 89.99956]
   [89.99956 89.99956]]

  [[89.99956 89.99956]
   [89.99956 89.99956]]]


 [[[89.99956 89.99956]
   [89.99956 89.99956]]

  [[89.99956 89.99956]
   [89.99956 89.99956]]]


 [[[89.99956 89.99956]
   [89.99956 89.99956]]

  [[89.99956 89.99956]
   [89.99956 89.99956]]]


 [[[89.99956 89.99956]
   [89.99956 89.99956]]

  [[89.99956 89.99956]
   [89.99956 89.99956]]]]
